import type { Metadata } from "next";
import {Roboto}  from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Roboto({ subsets: ["latin"],weight:"300" });

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar/>
        {children}
        <Footer/>
        </body>
        
    </html>
  );
}
